In [5]:
print("space")

space

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/space_decay.csv")

In [7]:
df.info

<bound method DataFrame.info of        CCSDS_OMM_VERS                            COMMENT        CREATION_DATE  \
0                   2  GENERATED VIA SPACE-TRACK.ORG API  2021-11-01T06:46:11
1                   2  GENERATED VIA SPACE-TRACK.ORG API  2021-11-01T04:58:37
2                   2  GENERATED VIA SPACE-TRACK.ORG API  2021-11-01T06:26:11
3                   2  GENERATED VIA SPACE-TRACK.ORG API  2021-10-31T18:07:15
4                   2  GENERATED VIA SPACE-TRACK.ORG API  2021-11-01T04:58:37
...               ...                                ...                  ...
14367               2  GENERATED VIA SPACE-TRACK.ORG API  2021-10-29T18:22:04
14368               2  GENERATED VIA SPACE-TRACK.ORG API  2021-10-31T18:06:35
14369               2  GENERATED VIA SPACE-TRACK.ORG API  2021-10-31T18:07:15
14370               2  GENERATED VIA SPACE-TRACK.ORG API  2021-10-31T18:07:15
14371               2  GENERATED VIA SPACE-TRACK.ORG API  2021-11-01T04:58:37

      ORIGINATOR           OBJECT_NAME   OBJECT_ID CENTER_NAME REF_FRAME  \
0        18 SPCS       ARIANE 42P+ DEB   1992-072J       EARTH      TEME
1        18 SPCS              SL-8 DEB   1979-028C       EARTH      TEME
2        18 SPCS                GSAT 1   2001-015A       EARTH      TEME
3        18 SPCS              CZ-4 DEB  1999-057MB       EARTH      TEME
4        18 SPCS              CZ-4 DEB  1999-057MC       EARTH      TEME
...          ...                   ...         ...         ...       ...
14367    18 SPCS  TBA - TO BE ASSIGNED         NaN       EARTH      TEME
14368    18 SPCS  TBA - TO BE ASSIGNED         NaN       EARTH      TEME
14369    18 SPCS  TBA - TO BE ASSIGNED         NaN       EARTH      TEME
14370    18 SPCS  TBA - TO BE ASSIGNED         NaN       EARTH      TEME
14371    18 SPCS  TBA - TO BE ASSIGNED         NaN       EARTH      TEME

      TIME_SYSTEM MEAN_ELEMENT_THEORY  ... RCS_SIZE  COUNTRY_CODE  \
0             UTC                SGP4  ...   MEDIUM            FR
1             UTC                SGP4  ...    SMALL           CIS
2             UTC                SGP4  ...    LARGE           IND
3             UTC                SGP4  ...    SMALL           PRC
4             UTC                SGP4  ...    SMALL           PRC
...           ...                 ...  ...      ...           ...
14367         UTC                SGP4  ...      NaN           NaN
14368         UTC                SGP4  ...      NaN           NaN
14369         UTC                SGP4  ...      NaN           NaN
14370         UTC                SGP4  ...      NaN           NaN
14371         UTC                SGP4  ...      NaN           NaN

       LAUNCH_DATE   SITE  DECAY_DATE     FILE      GP_ID  \
0           1992.0  FRGUI         NaN  3195178  188614016
1           1979.0  PKMTR         NaN  3194950  188593285
2           2001.0    SRI         NaN  3195026  188609573
3           1999.0    TSC         NaN  3194431  188556894
4           1999.0    TSC         NaN  3194950  188592541
...            ...    ...         ...      ...        ...
14367          NaN    NaN         NaN  3191411  188414015
14368          NaN    NaN         NaN  3194430  188550573
14369          NaN    NaN         NaN  3194431  188561362
14370          NaN    NaN         NaN  3194431  188561387
14371          NaN    NaN         NaN  3194950  188596191

                    TLE_LINE0  \
0           0 ARIANE 42P+ DEB
1                  0 SL-8 DEB
2                    0 GSAT 1
3                  0 CZ-4 DEB
4                  0 CZ-4 DEB
...                       ...
14367  0 TBA - TO BE ASSIGNED
14368  0 TBA - TO BE ASSIGNED
14369  0 TBA - TO BE ASSIGNED
14370  0 TBA - TO BE ASSIGNED
14371  0 TBA - TO BE ASSIGNED

                                               TLE_LINE1  \
0      1 26741U 92072J   21304.94919376  .00000883  0...
1      1 26743U 79028C   21304.68908982  .00000079  0...
2      1 26745U 01015A   21305.22411368 -.00000165  0...
3      1 26754U 99057MB  21304.46625230  .00002265  0...
4      1 26755U 99057MC  21304.74081807  .00002610  0...
...                                                  ...
14367  1 87970U          21285.56271139 +.00354808 +0...
14368  1 89171U          21304.27943186 +.00020950 +0...
14369  1 T0007U          21304.15669309 -.00000068  0...
14370  1 T0207U          21304.37554955  .00000690  0...
14371  1 T0288U          21304.79318280 -.00000108  0...

                                               TLE_LINE2
0      2 26741   7.7156  90.2410 6528926 243.1216  38...
1      2 26743  82.9193 299.1120 0030720 158.9093 201...
2      2 26745  12.1717  16.5368 0237386 250.1248 146...
3      2 26754  98.4781   8.7205 0060618  37.3771 323...
4      2 26755  98.4232 122.0724 0062255 345.1605  27...
...                                                  ...
14367  2 87970  99.0098 214.6827 0011899 219.1613 140...
14368  2 89171  99.0272 141.1159 0055597  76.8926 283...
14369  2 T0007  31.9916 262.9339 0566728 162.7824 199...
14370  2 T0207  98.6758 348.3068 0058220 187.0288 173...
14371  2 T0288  90.2762 327.5871 0029565 238.9003 120...

[14372 rows x 40 columns]>

In [8]:
# Display first few rows
df.head(10)

,CCSDS_OMM_VERS,COMMENT,CREATION_DATE,ORIGINATOR,OBJECT_NAME,OBJECT_ID,CENTER_NAME,REF_FRAME,TIME_SYSTEM,MEAN_ELEMENT_THEORY,...,RCS_SIZE,COUNTRY_CODE,LAUNCH_DATE,SITE,DECAY_DATE,FILE,GP_ID,TLE_LINE0,TLE_LINE1,TLE_LINE2
0,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T06:46:11,18 SPCS,ARIANE 42P+ DEB,1992-072J,EARTH,TEME,UTC,SGP4,...,MEDIUM,FR,1992.0,FRGUI,NaN,3195178,188614016,0 ARIANE 42P+ DEB,1 26741U 92072J 21304.94919376 .00000883 0...,2 26741 7.7156 90.2410 6528926 243.1216 38...
1,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T04:58:37,18 SPCS,SL-8 DEB,1979-028C,EARTH,TEME,UTC,SGP4,...,SMALL,CIS,1979.0,PKMTR,NaN,3194950,188593285,0 SL-8 DEB,1 26743U 79028C 21304.68908982 .00000079 0...,2 26743 82.9193 299.1120 0030720 158.9093 201...
2,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T06:26:11,18 SPCS,GSAT 1,2001-015A,EARTH,TEME,UTC,SGP4,...,LARGE,IND,2001.0,SRI,NaN,3195026,188609573,0 GSAT 1,1 26745U 01015A 21305.22411368 -.00000165 0...,2 26745 12.1717 16.5368 0237386 250.1248 146...
3,2,GENERATED VIA SPACE-TRACK.ORG API,2021-10-31T18:07:15,18 SPCS,CZ-4 DEB,1999-057MB,EARTH,TEME,UTC,SGP4,...,SMALL,PRC,1999.0,TSC,NaN,3194431,188556894,0 CZ-4 DEB,1 26754U 99057MB 21304.46625230 .00002265 0...,2 26754 98.4781 8.7205 0060618 37.3771 323...
4,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T04:58:37,18 SPCS,CZ-4 DEB,1999-057MC,EARTH,TEME,UTC,SGP4,...,SMALL,PRC,1999.0,TSC,NaN,3194950,188592541,0 CZ-4 DEB,1 26755U 99057MC 21304.74081807 .00002610 0...,2 26755 98.4232 122.0724 0062255 345.1605 27...
5,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T06:36:11,18 SPCS,CZ-4 DEB,1999-057MD,EARTH,TEME,UTC,SGP4,...,SMALL,PRC,1999.0,TSC,NaN,3195096,188611545,0 CZ-4 DEB,1 26756U 99057MD 21305.20236010 .00000218 0...,2 26756 98.7597 287.9689 0085229 54.5300 306...
6,2,GENERATED VIA SPACE-TRACK.ORG API,2021-10-31T18:07:15,18 SPCS,XM-1,2001-018A,EARTH,TEME,UTC,SGP4,...,LARGE,US,2001.0,SEAL,NaN,3194431,188557395,0 XM-1,1 26761U 01018A 21304.53088963 .00000074 0...,2 26761 4.6906 78.1846 0003470 223.9574 172...
7,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T04:58:37,18 SPCS,BLOCK DM-SL R/B,2001-018B,EARTH,TEME,UTC,SGP4,...,LARGE,SEAL,2001.0,SEAL,NaN,3194950,188593042,0 BLOCK DM-SL R/B,1 26762U 01018B 21304.81461606 .00000024 0...,2 26762 1.3497 331.9982 7052274 336.4349 76...
8,2,GENERATED VIA SPACE-TRACK.ORG API,2021-10-25T02:11:01,18 SPCS,TITAN 3C TRANSTAGE DEB,1965-108AS,EARTH,TEME,UTC,SGP4,...,SMALL,US,1965.0,AFETR,NaN,3182768,188090800,0 TITAN 3C TRANSTAGE DEB,1 26763U 65108AS 21297.89618463 -.00000033 0...,2 26763 26.0813 147.4319 6743901 62.8851 354...
9,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T04:58:37,18 SPCS,INTELSAT 10 (PAS 10),2001-019A,EARTH,TEME,UTC,SGP4,...,LARGE,US,2001.0,TTMTR,NaN,3194950,188592542,0 INTELSAT 10 (PAS 10),1 26766U 01019A 21304.68108497 .00000046 0...,2 26766 5.0375 75.2284 0003655 162.7420 225...

In [9]:
df.columns.tolist()

['CCSDS_OMM_VERS',
 'COMMENT',
 'CREATION_DATE',
 'ORIGINATOR',
 'OBJECT_NAME',
 'OBJECT_ID',
 'CENTER_NAME',
 'REF_FRAME',
 'TIME_SYSTEM',
 'MEAN_ELEMENT_THEORY',
 'EPOCH',
 'MEAN_MOTION',
 'ECCENTRICITY',
 'INCLINATION',
 'RA_OF_ASC_NODE',
 'ARG_OF_PERICENTER',
 'MEAN_ANOMALY',
 'EPHEMERIS_TYPE',
 'CLASSIFICATION_TYPE',
 'NORAD_CAT_ID',
 'ELEMENT_SET_NO',
 'REV_AT_EPOCH',
 'BSTAR',
 'MEAN_MOTION_DOT',
 'MEAN_MOTION_DDOT',
 'SEMIMAJOR_AXIS',
 'PERIOD',
 'APOAPSIS',
 'PERIAPSIS',
 'OBJECT_TYPE',
 'RCS_SIZE',
 'COUNTRY_CODE',
 'LAUNCH_DATE',
 'SITE',
 'DECAY_DATE',
 'FILE',
 'GP_ID',
 'TLE_LINE0',
 'TLE_LINE1',
 'TLE_LINE2']

In [10]:
len(df)

14372

In [11]:
from datetime import datetime

# Convert DECAY_DATE to datetime
df['DECAY_DATE'] = pd.to_datetime(df['DECAY_DATE'], errors='coerce')

# Get today's date
today = pd.Timestamp(datetime.utcnow().date())

# Keep rows where:
# - DECAY_DATE is NaT (no decay recorded) OR
# - DECAY_DATE is in the future
df_active = df[(df['DECAY_DATE'].isna()) | (df['DECAY_DATE'] > today)].copy()

print("Remaining objects in orbit:", df_active.shape[0])

Remaining objects in orbit: 14372

C:\Users\BAHNIMAN\AppData\Local\Temp\ipykernel_18336\2668922156.py:7: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  today = pd.Timestamp(datetime.utcnow().date())

In [12]:
from datetime import datetime

# Ensure DECAY_DATE is parsed as datetime
df['DECAY_DATE'] = pd.to_datetime(df['DECAY_DATE'], errors='coerce')

# Get today's date
today = pd.Timestamp(datetime.utcnow().date())

# Filter rows where DECAY_DATE is in the future
df_future_decay = df[df['DECAY_DATE'] > today]

# Number of objects expected to decay in the future
print("Objects with future DECAY_DATE:", len(df_future_decay))

Objects with future DECAY_DATE: 0

C:\Users\BAHNIMAN\AppData\Local\Temp\ipykernel_18336\2565027655.py:7: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  today = pd.Timestamp(datetime.utcnow().date())

In [13]:
# Count non-null (not NaN) values in DECAY_DATE column
non_nan_decay_dates = df['DECAY_DATE'].notna().sum()

print("Non-NaN DECAY_DATE entries:", non_nan_decay_dates)

Non-NaN DECAY_DATE entries: 0

In [14]:
# Count of NaN values in each column
missing_values = df.isna().sum()

# Filter and show only columns with at least 1 missing value
missing_values = missing_values[missing_values > 0]

# Display
print("Columns with missing values:\n")
print(missing_values.sort_values(ascending=False))

Columns with missing values:

DECAY_DATE      14372
RCS_SIZE          198
OBJECT_ID          39
COUNTRY_CODE       39
LAUNCH_DATE        39
SITE               39
dtype: int64

In [16]:
rcs_counts = df['RCS_SIZE'].value_counts(dropna=False)

# Extract specific counts
medium_count = rcs_counts.get('MEDIUM', 0)
small_count = rcs_counts.get('SMALL', 0)
large_count = rcs_counts.get('LARGE', 0)
nan_count = df['RCS_SIZE'].isna().sum()

# Print the results
print(f"'MEDIUM': {medium_count}")
print(f"'SMALL' : {small_count}")
print(f"'LARGE' : {large_count}")
print(f"NaN     : {nan_count}")

'MEDIUM': 1639
'SMALL' : 8346
'LARGE' : 4189
NaN     : 198

In [17]:
# Step 1: Check value counts
print("RCS_SIZE Value Counts:")
print(df['RCS_SIZE'].value_counts())

RCS_SIZE Value Counts:
RCS_SIZE
SMALL     8346
LARGE     4189
MEDIUM    1639
Name: count, dtype: int64

In [18]:
# # Step 2: Find mode (most frequent category)
rcs_mode = df['RCS_SIZE'].mode()[0]
print(f"\nMode of RCS_SIZE: {rcs_mode}")

# Step 3: Fill missing values with the mode
df['RCS_SIZE'].fillna(rcs_mode, inplace=True)


# Fill remaining fields with 'Unknown' for display purposes
fill_cols = ['OBJECT_ID', 'COUNTRY_CODE', 'LAUNCH_DATE', 'SITE']
df[fill_cols] = df[fill_cols].fillna('Unknown')

Mode of RCS_SIZE: SMALL

In [23]:
missing_values = df.isna().sum()
missing_values

CCSDS_OMM_VERS             0
COMMENT                    0
CREATION_DATE              0
ORIGINATOR                 0
OBJECT_NAME                0
OBJECT_ID                  0
CENTER_NAME                0
REF_FRAME                  0
TIME_SYSTEM                0
MEAN_ELEMENT_THEORY        0
EPOCH                      0
MEAN_MOTION                0
ECCENTRICITY               0
INCLINATION                0
RA_OF_ASC_NODE             0
ARG_OF_PERICENTER          0
MEAN_ANOMALY               0
EPHEMERIS_TYPE             0
CLASSIFICATION_TYPE        0
NORAD_CAT_ID               0
ELEMENT_SET_NO             0
REV_AT_EPOCH               0
BSTAR                      0
MEAN_MOTION_DOT            0
MEAN_MOTION_DDOT           0
SEMIMAJOR_AXIS             0
PERIOD                     0
APOAPSIS                   0
PERIAPSIS                  0
OBJECT_TYPE                0
RCS_SIZE                   0
COUNTRY_CODE               0
LAUNCH_DATE                0
SITE                       0
DECAY_DATE             14372
FILE                       0
GP_ID                      0
TLE_LINE0                  0
TLE_LINE1                  0
TLE_LINE2                  0
dtype: int64

In [24]:
df.head()

,CCSDS_OMM_VERS,COMMENT,CREATION_DATE,ORIGINATOR,OBJECT_NAME,OBJECT_ID,CENTER_NAME,REF_FRAME,TIME_SYSTEM,MEAN_ELEMENT_THEORY,...,RCS_SIZE,COUNTRY_CODE,LAUNCH_DATE,SITE,DECAY_DATE,FILE,GP_ID,TLE_LINE0,TLE_LINE1,TLE_LINE2
0,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T06:46:11,18 SPCS,ARIANE 42P+ DEB,1992-072J,EARTH,TEME,UTC,SGP4,...,MEDIUM,FR,1992.0,FRGUI,NaT,3195178,188614016,0 ARIANE 42P+ DEB,1 26741U 92072J 21304.94919376 .00000883 0...,2 26741 7.7156 90.2410 6528926 243.1216 38...
1,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T04:58:37,18 SPCS,SL-8 DEB,1979-028C,EARTH,TEME,UTC,SGP4,...,SMALL,CIS,1979.0,PKMTR,NaT,3194950,188593285,0 SL-8 DEB,1 26743U 79028C 21304.68908982 .00000079 0...,2 26743 82.9193 299.1120 0030720 158.9093 201...
2,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T06:26:11,18 SPCS,GSAT 1,2001-015A,EARTH,TEME,UTC,SGP4,...,LARGE,IND,2001.0,SRI,NaT,3195026,188609573,0 GSAT 1,1 26745U 01015A 21305.22411368 -.00000165 0...,2 26745 12.1717 16.5368 0237386 250.1248 146...
3,2,GENERATED VIA SPACE-TRACK.ORG API,2021-10-31T18:07:15,18 SPCS,CZ-4 DEB,1999-057MB,EARTH,TEME,UTC,SGP4,...,SMALL,PRC,1999.0,TSC,NaT,3194431,188556894,0 CZ-4 DEB,1 26754U 99057MB 21304.46625230 .00002265 0...,2 26754 98.4781 8.7205 0060618 37.3771 323...
4,2,GENERATED VIA SPACE-TRACK.ORG API,2021-11-01T04:58:37,18 SPCS,CZ-4 DEB,1999-057MC,EARTH,TEME,UTC,SGP4,...,SMALL,PRC,1999.0,TSC,NaT,3194950,188592541,0 CZ-4 DEB,1 26755U 99057MC 21304.74081807 .00002610 0...,2 26755 98.4232 122.0724 0062255 345.1605 27...

In [25]:
df.to_csv('data/cleaned_space_decay.csv', index=False)

In [26]:
df.to_pickle('data/cleaned_space_decay.pkl')